image: docker:latest

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_OPTS: "--insecure-registry=gitlab.vagrant.test:4567"
  DOCKER_HOST: "tcp://lordgaav__dind-options:2375"

services:
  - lordgaav/dind-options:latest

stages:
  - build
  - package
  - test
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn -Dmaven.test.failure.ignore -f pom.xml clean package -U"
  artifacts:
    paths:
      - target/*.jar
      - target/*.war
  tags:
    - docker

docker-build:
  stage: package
  script:
  - docker build -t gitlab.vagrant.test:4567/root/struts2-rce .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.vagrant.test:4567
  - docker push gitlab.vagrant.test:4567/root/struts2-rce
  tags:
    - docker

dependency_scanning:
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  script:
    - echo 1   database-server >> /etc/hosts
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]
  tags:
    - docker
